### ISSUE TITLE
Red on green is bad

### ISSUE THREAD

**Issue by stijnherreman** [serilog/serilog.github.io#2]
Red text on a green background is a classical bad colour combination. You get this effect when hovering the 'Installation' link.

Suggestion: remove the `font-weight: bold` for `a`, and replace `background-color: rgba(47, 237, 111, 1)` with `font-weight: bold` for `.highlight`.

Another small remark: the Reenie Beanie font makes text hard to read for no reason.

**Comment by nblumhardt** [comment]
Nice spotting, and thanks for the feedback.
