### ISSUE TITLE
Add link to source image for the serilog logo

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog.github.io#3]
I'm not quite sure what to do with this information, but I could find that the original image that was used for the Serilog logo is vailable here : 

https://thenounproject.com/term/sewing-needle/3135/

I just thought this should be written somewhere, in case someone somewhere needs to make a Serilog-inspired logo :)

**Comment by khellang** [comment]
It's mentioned in the [Serilog readme](https://github.com/serilog/serilog/blob/dev/README.md) 😄 

![image](https://user-images.githubusercontent.com/582487/36891495-24c2af82-1e02-11e8-8d4e-b134127f6647.png)

**Comment by tsimbalar** [comment]
Yep, it's credited, but the exact link to the image is not there :smile_cat:  :tophat:  :mag:

**Comment by nblumhardt** [comment]
It's also in here as SVG: https://github.com/serilog/serilog/tree/dev/assets (our modified version).

Not sure we need more outgoing links at this point - probably no harm in adding it, but also don't see much value, personally.

**Comment by tsimbalar** [comment]
Ah, I hadn't seen the svg version in the repo :) ... I guess it's just fine, then, I was just thinking that if for some reason we need some new icons, we would have to reverse engineer the existing PNGs :-P

Closing !
